jobs:
  build:
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v2
    - continue-on-error: true
      name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        distribution: adopt
        java-version: '11'
    - continue-on-error: true
      name: Build with Maven
      run: mvn --batch-mode --update-snapshots verify
    - continue-on-error: true
      name: Upload Artifact
      uses: actions/upload-artifact@v2
      with:
        name: nuclei-burp-plugin-SNAPSHOT-build
        path: target/nuclei-burp-plugin-1.1.2-SNAPSHOT-jar-with-dependencies.jar
name: Java CI
on:
  repository_dispatch:
    types: trigger-ga___ci.yaml
